debg message on libcudnn
Signed-off-by: Anh Uong <anh.uong@ibm.com>

diff --git a/build/Dockerfile b/build/Dockerfile
--- a/build/Dockerfile
+++ b/build/Dockerfile
@@ -121,7 +121,9 @@ RUN /usr/local/cuda/bin/nvcc --version || echo "failed"
 RUN cat /usr/lib/cuda/version.txt || echo "failed"
 RUN cat /proc/driver/nvidia/version || echo "failed"
 RUN nvidia-smi || echo "failed"
-RUN dnf install -y libcudnn9 libcudnn9-dev
+RUN ls /usr/local/lib/python${PYTHON_VERSION}/site-packages/nvidia/cudnn/lib || echo "failed"
+RUN dnf list installed | grep cuda
+RUN dnf install -y libcudnn9 || echo "failed"
 
 RUN dnf install -y git && \
     # perl-Net-SSLeay.x86_64 and server_key.pem are installed with git as dependencies
